# Introducción a numpy [link](http://www.python-course.eu/numpy.php)

### Comparación de tiempos entre python standard,  python numpy, numba compiler



In [1]:
import numpy
import time
from numba import jit

def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = numpy.arange(10000000)
    Y = numpy.arange(10000000)
    Z = X + Y
    return time.time() - t1

@jit
def numba_version():
    t1 = time.time()
    X = numpy.arange(10000000)
    Y = numpy.arange(10000000)
    Z = X + Y
    return time.time() - t1


In [2]:
time_trad = trad_version()
print(time_trad)

20.8193039894104


In [3]:
time_np = numpy_version()
print(time_np)

0.7231082916259766


In [4]:
time_nu = numba_version()
print(time_nu)

0.17617177963256836


In [7]:
print("trad/numpy", time_trad/time_np)
print("numpy/numba", time_np/time_nu)
print("trad/numba", time_trad/time_nu)

trad/numpy 28.791405423655494
numpy/numba 4.104563699896335
trad/numba 118.1761575709348


# Creación de arrays en Numpy

Si hacemos una busqueda con "python numpy" como parámetro, el resultado muestra que la creación de array está dentro de los primeros resultados.

In [44]:
a = [2,3,1,0]
print (a)
x = numpy.array([2,3,1,0])
print (x)  # notar la diferencia en la salida del print
x = numpy.array([[1,2.0],[0,0],(1+1j,3.)]) # notar el mix de tuplas, listas y tipos
print("%s %d %s"%(x, x.ndim, x.shape))  # ndim: dimensión del array, shape: col x filas

# creada con enteros
x = numpy.array([42,47,11], int)
print ("int ", x)

# creada con enteros
x = numpy.array([42,47,11], float)
print ("float ", x)

# Una matriz llena con ceros
x = numpy.zeros((2, 3)) 
print(x)
# 6 valores equiespaciados entre 1 y 4: linspace
x = numpy.linspace(1., 4., 6)
print(x)

#  3 D
x=numpy.empty((2,3,5))
x=numpy.arange(30).reshape(2,3,5)
x = numpy.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],
       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

print (x)
print ()
print ()

# vamos a ver que de esta manera 
# no es la mejor forma de iterar
# el array
for e in x:
    print ("n1")
    print (e)
    for e2 in e:
        print ("n2")
        print (e2)
        for e3 in e2:
            print("n3")
            print (e3)
# sumar una constante a todos los elementos del array
y = x + 2
print (y)

# lo mismo con la multiplicación por una constante
y = y * 2

#
# No hay que iterar sobre todos los elementos
#

[2, 3, 1, 0]
[2 3 1 0]
[[ 1.+0.j  2.+0.j]
 [ 0.+0.j  0.+0.j]
 [ 1.+1.j  3.+0.j]] 2 (3, 2)
int  [42 47 11]
float  [ 42.  47.  11.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[ 1.   1.6  2.2  2.8  3.4  4. ]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


n1
[[0 1 2]
 [3 4 5]
 [6 7 8]]
n2
[0 1 2]
n3
0
n3
1
n3
2
n2
[3 4 5]
n3
3
n3
4
n3
5
n2
[6 7 8]
n3
6
n3
7
n3
8
n1
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
n2
[ 9 10 11]
n3
9
n3
10
n3
11
n2
[12 13 14]
n3
12
n3
13
n3
14
n2
[15 16 17]
n3
15
n3
16
n3
17
[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


# Rutinas de creación de arrays [link](http://docs.scipy.org/doc/numpy/reference/routines.array-creation.html#routines-array-creation)

## Unos y ceros

## Desde datos existentes

## Rangos numéricos

## Construcción de matríces

## La clase matrix

## Otras

### Son raras

# Broadcasting

### Las reglas del broadcasting 
* Array Broadcasting in numpy [link](http://wiki.scipy.org/EricsBroadcastingDoc)
* Broadcasting [link](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html)

En una operación entre 2 arreglos, Numpy intenta que el arreglo de menor dimensión adquiera las dimensiones del mayor y realizar la operación.

In [49]:
a = numpy.array([1.0, 2.0, 3.0])
b = numpy.array([2.0, 2.0, 2.0])
print(a*b)
b = 2.0
print(a*b, b)

b = numpy.array([2])
print(a*b, b)

#  3 D
x=numpy.empty((2,3,5))
x=numpy.arange(30).reshape(2,3,5)
print(x)

print()
y = numpy.array([2,1,3,1,2])
print ("y*x broadcasted")
print()
print (y*x)

# repeat
print("repeat --->")
print(y.repeat(2))
z= numpy.tile(y,(3, 1))
print("tile .....", z.shape, x.shape)
print(z*x)



# genera error
z= numpy.tile(y,(2, 1))
print(z*x)

# también genera error
w = numpy.array([2,1])
v = numpy.tile(w,(3,1))
print (v*x)

[ 2.  4.  6.]
[ 2.  4.  6.] 2.0
[ 2.  4.  6.] [2]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

y*x broadcasted

[[[ 0  1  6  3  8]
  [10  6 21  8 18]
  [20 11 36 13 28]]

 [[30 16 51 18 38]
  [40 21 66 23 48]
  [50 26 81 28 58]]]
repeat --->
[2 2 1 1 3 3 1 1 2 2]
tile ..... (3, 5) (2, 3, 5)
[[[ 0  1  6  3  8]
  [10  6 21  8 18]
  [20 11 36 13 28]]

 [[30 16 51 18 38]
  [40 21 66 23 48]
  [50 26 81 28 58]]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,3,5) 

## nditer 

Efficient multi-dimensional iterator object to iterate over arrays

In [65]:
a = numpy.arange(6).reshape(2,3)
print (a)
for x in numpy.nditer(a.copy(order='F')):
    print(x)
    
print ("------------------")
for x in numpy.nditer(a):
    print(x)
 
# una manera de acceder a cada uno de los elementos
# del array
for x in numpy.nditer(a, op_flags=['readwrite']):
   x[...] = 2 * x

print (a)

it = numpy.nditer(a, flags=['f_index'])

while not it.finished:
    print ("%d <%d>" % (it[0], it.index))
    it.iternext()

[[0 1 2]
 [3 4 5]]
0
3
1
4
2
5
------------------
0
1
2
3
4
5
[[ 0  2  4]
 [ 6  8 10]]
0 <0>
2 <2>
4 <4>
6 <1>
8 <3>
10 <5>
